---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - linkerd-dynauth.k.r8y.net
  resources:
  - dynamicserverauthorizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - linkerd-dynauth.k.r8y.net
  resources:
  - dynamicserverauthorizations/finalizers
  verbs:
  - update
- apiGroups:
  - linkerd-dynauth.k.r8y.net
  resources:
  - dynamicserverauthorizations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.linkerd.io/v1beta1
  resources:
  - serverauthorizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
