apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: linkerd-dynauth.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DynamicServerAuthorization is the Schema for the dynamicserverauthorizations
        API
      displayName: Dynamic Server Authorization
      kind: DynamicServerAuthorization
      name: dynamicserverauthorizations.linkerd-dynauth.k.r8y.net
      version: v1alpha1
  description: Provide a couple ways to dynamically authorize linkerd servers.
  displayName: linkerd Dynamic Authorizer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - linkerd
  - dynamic authorization
  - server authorization
  links:
  - name: Linkerd Dynauth
    url: https://linkerd-dynauth.domain
  maintainers:
  - email: ripta@users.noreply.github.com
    name: Ripta Pasay
  maturity: alpha
  provider:
    name: linkerd-dynauth
    url: https://github.com/ripta/linkerd-dynauth
  version: 0.0.0
